server:
  port: 8386
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  application:
    name: quotes-facts-service
  datasource:
    url: jdbc:mysql://db-mysql-sgp1-do-user-8499874-0.m.db.ondigitalocean.com:25060/gvsdb?sslMode=REQUIRED
    username: doadmin
    password: AVNS_jHgFuyfc1f-mq4KTLJ0
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"

springdoc:
  show-actuator: true
  api-docs:
    path: /authentication-service/v3/api-docs
  swagger-ui:
    enabled: true
    url: /authentication-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers, env

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: application.log
myapp:
  message: Hello, Spring Boot!

